#!/bin/sh

set -ex

go fmt ./...
go vet ./...
go build ./...
# -race + -count=1 matches the CI test invocation so a passing
# precommit isn't shadowed by a failing CI run.
go test -race -count=1 ./...

git status
